# Generated by Django 3.0.9 on 2020-09-21 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20200917_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='place',
            new_name='state',
        ),
    ]
